services:

  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token  # Root token for development
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_UI: "true"

    volumes:
      - vault-data:/vault/data  # Persistent storage for Vault data
      - ./init-vault.sh:/init-vault.sh  # Mount the script into the container
    networks:
      operation-portal-network:
        aliases:
          - vault
    entrypoint: [ "sh", "-c", "vault server -dev" ]

  vault-client:
    image: hashicorp/vault
    container_name: vault-client
    ports:
      - "8300:8200"
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root-token"
      VAULT_UI: "true"
    volumes:
      - ./init-vault.sh:/init-vault.sh  # Ensure script exists and is executable
    entrypoint: [ "sh", "/init-vault.sh" ]  # Run initialization script
    depends_on:
      - vault
    networks:
      operation-portal-network:
        aliases:
          - vault-client

  # Redis Service
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    depends_on:
      - vault
      - vault-client
    networks:
      operation-portal-network:
        aliases:
          - redis

  mysql-operation-portal:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql-operation-portal-data:/var/lib/mysql
    depends_on:
      - vault
      - vault-client
    networks:
      operation-portal-network:
        aliases:
          - mysql-operation-portal

  mysql-central-ledger:
    image: mysql:8.0
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql-central-ledger-data:/var/lib/mysql
    depends_on:
      - vault
      - vault-client
    networks:
      operation-portal-network:
        aliases:
          - mysql-central-ledger

  # OPERATION Portal Application
  operation-portal:
    image: operation-portal
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8003:8003
    networks:
      operation-portal-network:
        aliases:
          - operation-portal
    depends_on:
      - vault
      - vault-client
      - redis
      - mysql-operation-portal
      - mysql-central-ledger
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root-token
      ENGINE_PATH: operation_portal
      OPERATION_PORTAL_PORT_NO: 8003
      CENTRAL_LEDGER_ENDPOINT: https://google.com
      SETTLEMENT_ENDPOINT: https://google.com
      OPERATION_PORTAL_FRONTEND_ENDPOINT: https://google.com
      REPORT_PAGE_SIZE: 100000


volumes:
  vault-data:
  redis-data:
  mysql-operation-portal-data:
  mysql-central-ledger-data:

networks:
  operation-portal-network:
    driver: bridge

