INSERT INTO tbl_menu (menu_id, name, parent_id, is_active, created_date, updated_date) VALUES
(1, 'Operational Portal', 0, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(2, 'Home', 1, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(3, 'Participants', 1, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(4, 'Participant Positions', 3, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(5, 'Participant', 3, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(6, 'User Management', 1, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(7, 'Users', 6, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(8, 'Transfers', 1, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(9, 'Settlement', 1, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(10, 'Settlement Models', 9, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(11, 'Settlement Windows', 9, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(12, 'Finalize Settlement', 9, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(13, 'Reports', 1, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(14, 'Settlement Bank Report', 13, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(15, 'Settlement Detail Report', 13, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(16, 'Settlement Summary Report', 13, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(17, 'Settlement Statement Report', 13, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(18, 'Settlement Audit Report', 13, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(19, 'Audit Report', 13, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(20, 'Pending Approvals', 1, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(21, 'Audit', 1, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(22, 'Support Center', 1, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

